### PR TITLE
Resolves https://github.com/symless/synergy/issues/3705

### PR DESCRIPTION
**Pull request by spurin**
Resolves issue 3705, successfully tested with Mac as server alongside Windows/Ubuntu clients, able to switch between any systems as expected, log output:

```
[2016-08-03T20:54:18] INFO: switch from "Jamess-MacBook-Pro.local" to "Jamess-MacBook-Pro.local" at 739,827
    /Users/james/Desktop/synergy_fix/synergy/src/lib/server/Server.cpp,463
[2016-08-03T20:54:21] INFO: switch from "Jamess-MacBook-Pro.local" to "Alpha-841W322" at 615,173
    /Users/james/Desktop/synergy_fix/synergy/src/lib/server/Server.cpp,463
[2016-08-03T20:54:21] INFO: leaving screen
    /Users/james/Desktop/synergy_fix/synergy/src/lib/synergy/Screen.cpp,131
[2016-08-03T20:54:21] WARNING: cursor may not be visible
    /Users/james/Desktop/synergy_fix/synergy/src/lib/platform/OSXScreen.cpp,2180
[2016-08-03T20:54:21] INFO: screen "Jamess-MacBook-Pro.local" updated clipboard 0
    /Users/james/Desktop/synergy_fix/synergy/src/lib/server/Server.cpp,1544
[2016-08-03T20:54:21] INFO: screen "Jamess-MacBook-Pro.local" updated clipboard 1
    /Users/james/Desktop/synergy_fix/synergy/src/lib/server/Server.cpp,1544
[2016-08-03T20:54:22] INFO: switch from "Alpha-841W322" to "james-PowerEdge-T20" at 562,310
    /Users/james/Desktop/synergy_fix/synergy/src/lib/server/Server.cpp,463
[2016-08-03T20:54:30] INFO: switch from "james-PowerEdge-T20" to "Alpha-841W322" at 615,173
    /Users/james/Desktop/synergy_fix/synergy/src/lib/server/Server.cpp,463
[2016-08-03T20:54:30] INFO: switch from "Alpha-841W322" to "Jamess-MacBook-Pro.local" at 739,827
    /Users/james/Desktop/synergy_fix/synergy/src/lib/server/Server.cpp,463
[2016-08-03T20:54:30] INFO: entering screen
    /Users/james/Desktop/synergy_fix/synergy/src/lib/synergy/Screen.cpp,113
```

### CODE REVIEW

**Comment by manijak** [comment]
This is so unprofessional... I mean, Synergy was made aware of the issue in 2014! Almost two years ago... Please, merge the fix so we can start using the product we paid for, please.

**Comment by hovissimo** [comment]
@manijak The "maintainers" are a bit of a joke.  This PR was set to pr-review a day after the very last commit made to master 28 days ago. (See: https://github.com/symless/synergy/commits/master)  It appears that nobody with write access has even glanced at this project in the last month.

Sorry about that money you spent.  I'm certainly sorry I gave them mine.

**Comment by spurin** [comment]
What's the latest on this?  I see that an update for 1.8.3 has been announced via email and it states that 'Media Keys now work on mac'.  Has anyone tested the fix in this thread against the latest build, presumably 1.8.4?  

@nylan states that 'The impact of this change has to be determined before we commit' in https://github.com/symless/synergy/issues/3705 ... outside of this comment, there's no context on what this actually means?  Anyone care to elaborate?

I'd think there should be more of a concern in understanding the impact of an unresolved issue that has been outstanding for two years, has received a multitude of negative comments and for many, including myself, renders the software unsuitable.

Personally, I'd like to be running 1.8.3 but am in need of this fix ... looks like I may have to spin up another homebrew DIY compile for now whilst this remains unresolved :(

p.s. still love the product :)

**Comment by XinyuHou** [comment]
@spurin 
Thank you for this PR.

Could you give us a bit more explanations. I see you remove the if statement and the comments that explain why it's there.

Sorry for the delays on this PR. We have to look into it then merge the changes in if it won't cause other side effects.

**Comment by spurin** [comment]
Hi @XinyuHou 

With the 'if' statement in place, hotkey functionality doesn't work.  In a 3 system setup, with a Mac as the server and a corresponding hotkey configured for each system, F1 = Mac, F2 = Windows, F3 = Linux.

Mac to Windows = False
Mac to Ubuntu = False
Windows to Mac = True
Windows to Ubuntu = True
Ubuntu to Mac = True
Ubuntu to Windows = True

In a nutshell, as soon as your keyboard and mouse are on the Mac, hotkeys defined in Synergy no longer work.

I removed the comments as they were unclear.  Initially when I started the work on this I tried to understand the meaning of the comment with a view of incorporating the intention of the original author (apologies for the lack of recognition, I did look at git blame but this looks like transitioned code from SF, back in 2009).  There were two scenarios I could see relating to this comment ...

A)  The reference to 'secondary screen' refers to a secondary screen on the Mac, a scenario in which I have with both my laptop and external screen.  Why would I want the hotkey to function differently when I'm on my external screen to my primary screen?  That sounds like a very niche use case and one that doesn't apply to most users

B) The reference to 'secondary screen' refers to another computer, i.e. in the example given, the Windows or Ubuntu host.  Given the issue detailed above, the symptoms lean more towards this, however with that being said, in my tests with the pull request code in place, I've not encountered any keyboard combinations using my mac keyboard with my mac, other than the hotkey (in my case F1) that get passed back through to the Mac host as desired.

With this in mind, I believe the functionality may be working as expected with the pull request in place, making the if/comment section unnecessary.

If this is not the case and there is a scenario that this equates too, please advise and I can test accordingly.

**Comment by spurin** [comment]
@XinyuHou @nbolton  It would be appreciated if we can get this issue labelled accordingly so it's in scope for an actual resolution sometime soon, i.e. within the next two releases (it's already been outstanding for 2+ years despite the 'pr-review' tag).

Like others, I've paid for the software and found it to be flawed for my use case by this particular bug ... not only that I've spent time trying to resolve this issue, I've provided a patch which works, has had feedback from others as resolving the issue and I've also responded in detail to your requests asking for further explanations.

At present, I can't update to your latest version because of this issue.

Could you please provide the common courtesy and reply to the thread and/or set the wheels in motion for it's inclusion/resolution.  As before, I'm willing to help but that involves a two way conversation.

**Comment by spurin** [comment]
@nbolton contacted me via email as I had a support case open for this issue, for reference it said the following "Hi James, I'm really sorry for the delay.  I have prioritized your ticket, it's now high priority.  You'll hear from us soon.  Thanks, Nick".  So, fingers crossed, the fix may make it into 1.8.5

**Comment by spurin** [comment]
Merged upstream, resolving the conflict with the filename change for OSXScreen.mm

**Comment by spurin** [comment]
@nbolton @XinyuHou - Is this actually being looked at or am I going to receive another release email even after the last promise of it being prioritised?  

The issues discussion https://github.com/symless/synergy/issues/3705 lists this as bug/priority-2-next whilst it's still listed here as pr-review.  I added the fix which has been confirmed as working by other interested parties on August 3rd, giving plenty of time for review, yet it seems to have received no progression.  I've also answered in detail the concerns that you raised.

The merge subsequently incurred conflicts as the codebase was refactored.  I've fixed the merge to fall in line with upstream changes.

I received recently, a marketing email with regards to updating to Pro for a small cost and am keen to upgrade, the SSL functionality that you mention sounds good, however .. I'm not going to pay for an update to what is without this fix, a broken product.

It's been a problem now for more than 2 years and for people like myself and the many others voicing their concern, it renders the product unusable, please take the 2 minutes to review the PR and progress accordingly with testing.  

As per comments in the related thread, myself and a number of people have already confirmed that the compiled version that I provided with the fix resolves the issue in question.  Any talk of this being resolved also receives positive feedback from the community.  Let's get this tested and wrapped up please ... Winter is coming.

**Comment by Celant** [comment]
Hey @spurin sorry for all the delays.

Can you re-submit this PR on the branch 'pr-5522-hotkey' and I'll merge it for you.

**Comment by spurin** [comment]
Thanks @Celant I've updated the base as requested.

**Comment by spurin** [comment]
Done, thank you

**Comment by spurin** [comment]
@Celant @XinyuHou - what's happened here?  This discussion has been closed, the requested branch is no longer and I don't see any changes in the other branches.

**Comment by Celant** [comment]
Sorry @spurin, there was some miscommunication between Jerry and I.

Merged, I'll post the built binaries here shortly.

**Comment by Celant** [comment]
Builds available to test here: http://symless.com/nightly?filter=f4d9faa

**Comment by spurin** [comment]
Thanks @Celant

**Comment by divby1** [comment]
@spurin You are my new personal hero, many thanks!

**Comment by spurin** [comment]
Hi @Celant,

Can we please progress this into master now, the feedback has been positive above, and in the other threads.

**Comment by spurin** [comment]
@Celant @nbolton @nlyan @XinyuHou  : Can we please push forward to get this into a public release now, we've got a general consensus with the feedback above and also the positive feedback on https://github.com/symless/synergy/issues/3705

There's no reason not to get this in and it's been outstanding no for years!

People like myself are having to rely on the 1.8.6 nightly build and one that I'm having to host for myself at the moment to get round what is a very frustrating issue.

Further to this, because of the release to 1.8.7, it breaks the 'Pro' functionality when having to use 1.8.6, functionality which I personally have paid for to get SSL support.  When it checks for updates it seems to disable the Pro functionality and you need to re-activate it...

I for one, want to be able to download the latest version and use it as expected.

**Pull request merged**
