### PR TITLE
High resolution App icon on Mac

### PR DESCRIPTION
**Pull request by amandamcg**
Redid mac app icon based on the logo on the website. (Synergy.icns)
logo-large

### CODE REVIEW

**Comment by XinyuHou** [comment]
Thanks for the pull request! Buildbot is now [building](http://buildbot.synergy-project.org/builders) your pull request (it usually takes about 30 minutes). When done, the packages will be automatically uploaded (http://synergy-project.org/nightly?filter=pr4828). Please test and let me know if it worked.

**Comment by amandamcg** [comment]
I tested this package: synergy-pr4828-alpha-5d9abf7-MacOSX1010-x86_64.dmg and it worked as intended.


screen shot 2015-08-03 at 2 44 25 pm
screen shot 2015-08-03 at 2 44 13 pm

**Comment by nbolton** [comment]
@XinyuHou Please prioritize for next 1.8 release.

**Comment by Socapex** [comment]
Note that Windows uses the old icon on the taskbar (not the notification area though). So if you pin it to the taskbar it is not super prettay ;)

**Comment by XinyuHou** [comment]
@Socapex @amandamcg 
Please test our nightly.
http://synergy-project.org/nightly?filter=pr4828-update-mac-app-icon-beta-b3594c5

**Comment by XinyuHou** [comment]
This PR should solve issue #5299

**Comment by XinyuHou** [comment]
Changes are merged into https://github.com/symless/synergy/tree/v1.8.2

**Pull request closed without merging**
