### PR TITLE
Remove auto Alt+Printscreen on Windows

### PR DESCRIPTION
**Pull request by foliveira**
As per issue https://github.com/symless/synergy/issues/4288

### CODE REVIEW

**Comment by the-wes** [comment]
I don't know about this. I see the function has been changed to use the keycode for PrintScreen rather than the "snapshot" virtual key. I just wonder if it was like that for a reason, or if there is a better virtual key we could use instead. Or am I just worrying too much?

**Comment by nbolton** [comment]
@the-wes Would you like us to use this one? Did you test it? @speaker

**Comment by EvzenP** [comment]
Almost a year after a fix was committed... and this damned bug is still present and driving me nuts every single day :(.
Will this fix ever be released? Are we waiting for the-wes, who doesn't seem to care anymore?

**Comment by shelwig** [comment]
This behavior is really frustrating. When will the fix be released?

**Comment by EvzenP** [comment]
Hello?!?! Anybody reading it here?! Can this be FINALLY released?!

**Comment by XinyuHou** [comment]
@foliveira 
I can't seem to create a branch for this PR. Any suggestion?

**Comment by ryan-codingintrigue** [comment]
@XinyuHou Can't you just create a new PR and reference this one? It's only 5 removed lines and would be a valuable fix.

**Pull request merged**
