### PR TITLE
Korean keyboard key support for alt_r, ctrl_r

### PR DESCRIPTION
**Pull request by crucifyer**
I can't compile with windows 8.1, visual studio 2013 x64
please, patch this and compile for me.
thank you.

### CODE REVIEW

**Comment by nbolton** [comment]
Thanks for the pull request! I created a branch for you (https://github.com/synergy/synergy/tree/pr-crucifyer-korean-key-fix). Buildbot is now [building](http://buildbot.synergy-project.org/builders) (it usually takes about 30 minutes). When done, the packages will be automatically uploaded (http://synergy-project.org/nightly?filter=pr-crucifyer-korean-key-fix). Happy testing!

**Comment by crucifyer** [comment]
thank you very much!!!!

**Comment by speaker** [comment]
There is a conflict between this and another pr: https://github.com/synergy/synergy/pull/4605

Can you recommend a common solution?

**Comment by crucifyer** [comment]
#4605 is better :)
remove my pr. thank you.

**Comment by crucifyer** [comment]
win 8.1 master slave #4605 didn't work.
#4475 work.

**Comment by twilight512** [comment]
Hi crucifyer,

Just wanted to double check that you updated both versions (server and client). I will be doing some testing tomorrow. Thanks!

Albert.

**Comment by speaker** [comment]
Once there is consensus on the patch, I'll integrate it.
The substantive differences I can see is the use of
kKeyAlt_R = 0xEFEA  vs  kKeyHangulEng = 0xEF31 
kKeyHanja = 0xEF34  vs  kKeyControl_R  = 0xEFE4

**Comment by twilight512** [comment]
OK, I've done some testing and figured out what the problem was. If you only have a Korean IME installed on Windows, then #4605 works fine, but if you have both an English keyboard IME and a Korean keyboard IME installed on the server machine, it seems to mess up the key codes. This doesn't happen with #4475 . Please merge #4475 instead of #4605 .

**Comment by twilight512** [comment]
On second thought, this may be because I am using a US keyboard. I think we will need to make sure the patch works for Korean keyboards also. Are you using a Korean keyboard crucifyer?

**Comment by crucifyer** [comment]
windows 8.1 korean version.
and, installed korean, japanese IME.

**Comment by twilight512** [comment]
I'm talking about the actual keyboard itself. Does your keyboard have Korean letters on it, as well as a 한/영 key?

**Comment by crucifyer** [comment]
please, build this for new version :)

**Comment by 335** [comment]
I was using the korean keyboard and test it.
It works well.

**Comment by ommokazza** [comment]
Does this patch working?
This does not working for Hangul/Hanja key of Korean 103/106 keyboard layout.

The virtual key code values of Hangul / Hanja key of 103/106 Korean Keyboard is same to Kana / Kanji of Japanese keyboard layout.

So we have to update the s_virtualKey table or check korean local in 
MSWindowsKeyState::getKeyId()... (like #5196)

**Comment by XinyuHou** [comment]
Duplicate to https://github.com/symless/synergy/pull/5196

**Pull request closed without merging**
