### PR TITLE
Mac OS X 10.10 configuration and build fix

### PR DESCRIPTION
**Pull request by juanpaulo**
Configuration and build fix for Yosemite.
1. Changed condition to read OSX_TARGET_MAJOR, OSX_TARGET_MAJOR, etc.
2. Dynamically get Qt library directory

### CODE REVIEW

**Comment by awesomebing1** [comment]
Thank you, this really helped me.

**Comment by speaker** [comment]
Thanks for the pull request! I created a branch for you (https://github.com/synergy/synergy/tree/pr-juanpaulo-os10-config-build-fix). Buildbot is now [building](http://buildbot.synergy-project.org/builders) (it usually takes about 30 minutes). When done, the packages will be automatically uploaded (http://synergy-project.org/nightly?filter=pr-juanpaulo-os10-config-build-fix). Happy testing!

**Comment by XinyuHou** [comment]
Thanks for the pull request! Buildbot is now [building](http://buildbot.synergy-project.org/builders) your pull request (it usually takes about 30 minutes). When done, the packages will be automatically uploaded (http://synergy-project.org/nightly?filter=pr4729). Please test and let me know if it worked.

**Comment by juanpaulo** [comment]
No issues so far. :+1:

**Comment by jakepetroules** [comment]
Don't merge this. It only auto-detects Qt 4; #4986 auto-detects the library directory for *all* Qt versions.

**Comment by XinyuHou** [comment]
Closed as it's duplicated to https://github.com/symless/synergy/pull/4986

**Pull request closed without merging**
