### PR TITLE
Korean and Japanese keyboards have same keycode

### PR DESCRIPTION
**Pull request by ommokazza**
(VK_HANGUL == VK_KANA and VK_HANJA == VK_KANJI)
But They have different X11 keysym.

So VK_HANGUL and VK_HANJA do not working on 103/106 korean keyboard layout in windows server and linux client

### CODE REVIEW

**Comment by XinyuHou** [comment]
@ommokazza 
Thank you for the pull request.

Is there an issue associated to this pull request?

**Comment by ommokazza** [comment]
@XinyuHou 
This pull request is fix for issue #3286, #3071.

I'm working to make more simple code and test code.

And i'm making additional fix for Hangul / Hanja problem.
In Korean 103/106 keyboard does not brake Hangul / Hanja key.
The scan code for Hangul / Hanja are F2 and F1.
So we can't recognize that keys up.

I'll build and testing them and commit new fix code.

**Comment by ommokazza** [comment]
@XinyuHou 

I have update the fix code add a test.

I'll make a new issue and pull request about 103/106 Korean keyboard issue
which does not generate break code from keyboard for Hangul/Hanja key.

**Comment by XinyuHou** [comment]
@ommokazza 
This is the nightly build from your PR. Please test it.

I will do some research about your changes and code reviews. If you could give me to some references, that would really helpful.

**Comment by legonigel** [comment]
@ommokazza I think @XinyuHou Meant to link to the nightly build for this pr [here http://synergy-project.org/nightly?filter=pr5196](http://synergy-project.org/nightly?filter=pr5196)

**Comment by ommokazza** [comment]
At first, I explain my code.

- Duplicated virtual key codes
This is the link of Windows' Virtual Key table.
https://msdn.microsoft.com/library/windows/desktop/dd375731(v=vs.85).aspx

You can see that VK_HANGUL and VK_KANA have same value.
VK_HANJA and VK_KANJI have same value also.

There is no duplicated value case except above two cases.
So I add exception codes to getKeyID() funtion.

I considered another ways like making additional virtual key table or updating s_virtualKey when setKeyLayout() is called.
But I thought there is no case except hangul_key case.
So I choose the shortest code.


- About locale identifier
https://msdn.microsoft.com/en-us/library/windows/desktop/dd318693(v=vs.85).aspx
You can see 0x0412 is Korean locale idendifier on this link.
I checked keyboard layout only once, so I did not add Constant Variable. And just add comment.

- extended key
VK_HANGUL / VK_HANJA do not need check 'extended key' bit.

- X11 keysyms
When I checked keysymdef.h file,
I found some different in keysymdef.h and key_types.h.
(Hangul: 0xff31, Hanja: 0xff34)
So I modified that, too.

**Comment by XinyuHou** [comment]
@legonigel 
Thank you. I forgot to paste the link.

http://synergy-project.org/nightly?filter=synergy-pr5196-fix-korean-and-japanese-keycode-beta-c68ebe4

**Comment by ommokazza** [comment]
I'm testing the nightly build version. And it looks good until now.
I have posted this on my Korean blog for who want to test this.
(But no comment. I don't know whether the another download it or not.)

**Comment by XinyuHou** [comment]
@ommokazza 
how is going with the feedback from your blog?

I just recreated a branch for your PR. Here is the nightly. Could you let me know if this fixes the problem?

**Comment by ommokazza** [comment]
@XinyuHou 
I have released serveral version of synergy with hangul-key patch for more than six month on my blog.
But there is no bug reported.

My blog site is http://azza.tistory.com

**Comment by ommokazza** [comment]
@XinyuHou 
It seems that 1.8.6 branch has a problem while it process hangul-english key.
(not only 'pr' branch)

When I press hangul key, it shows below log - cannot map key
---------
[2016-12-08T10:52:00] DEBUG1: hook: 0x00000015 0x01f20001
[2016-12-08T10:52:00] DEBUG1: hook: 0x06000015 0x01f20001
[2016-12-08T10:52:00] DEBUG1: hook: 0x07000015 0x01f20001
[2016-12-08T10:52:00] DEBUG1: event: Key char=0, vk=0x15, nagr=0, lParam=0x01f20001
[2016-12-08T10:52:00] DEBUG1: new mask: 0x2000
[2016-12-08T10:52:00] DEBUG1: new mask: 0x2000
[2016-12-08T10:52:00] DEBUG1: cannot map key
-------------

**Comment by ommokazza** [comment]
@XinyuHou
Oops, I'm sorry.
Ignore my previous comment please.
I'm confused this with pr5578.

I just installed this version and it looks good.
I'll report if there is a problem.

I have released serveral previous version of synergy with hangul-key patch
for more than six month on my blog. But there is no bug reported.
I'll share nightly version on my blog also.

My blog site is http://azza.tistory.com

**Comment by XinyuHou** [comment]
@ommokazza 
Thanks for your help.

Please give us some feedback so we can decide when to merge it into our next release.

**Comment by ommokazza** [comment]
@XinyuHou 
I'm update some code to handle shift-space key. 
It is used to change input mode in Korean keyboard layout.
And using virtual key table for Hangul, Hanja keys.

When I have checked VK_KANA and VK_KANJI,
They are not extended key. So they does not set extented bit.

So I can use 0x115 and 0x119 for VK_HANGUL, VK_HANJA.
They are extented key also.

**Comment by nlyan** [comment]
@ommokazza 

Can you test this build? http://symless.com/nightly?filter=4b913b5

**Comment by ommokazza** [comment]
@nlyan 
of course. i'll install and share it on my blog.

**Pull request merged**
