### PR TITLE
Add support for Visual Studio 11

### PR DESCRIPTION
**Pull request by chaironeko**
This is some work I have done to get things working with the latest version of Visual Studio, Qt, and Python.
It should be backwards compatable with previous build environments including Python2, and has been tested with the following new versions:
Visual Studio 2013 Community Version
Qt 5.4 (msvc2013_64_opengl)
Python 3.4.3
Wix Toolset 3.9.1208.0
CMake 3.2.2
Bonjour SDK 2.0.4.0
Windows 8.1

### CODE REVIEW

**Comment by chaironeko** [comment]
I just noticed you have another pull request for VC11 from wadetb as well.
I recommend taking his CMakeLists.txt and Common.h instead of mine. The changes are more or less equivalent but less sweeping.
My commands1.py should completely supercede his.
Would you like me to do a rebase onto his changes and do that merge for you?

**Comment by speaker** [comment]
@chaironeko , Sorry it's taken so long to get back to this pull request. We've been focused on stability of the 1.7.4 release. 

If you would be willing to merge the 2 sets of changes together that would be great. Also, I'm not sure how many of the changes in the diffs were specific to adding Visual Studio support and how many were unrelated style changes. Some editors we've encountered will beautify automatically, which is fine as long as they are beautifying to the synergy [coding style](https://github.com/synergy/synergy/wiki/Code-Style).

Thank you for the help!

**Comment by XinyuHou** [comment]
@chaironeko 
This is conflicting now. Could you please fix the conflict?

**Comment by XinyuHou** [comment]
Duplicate to https://github.com/symless/synergy/pull/5117

**Pull request closed without merging**
