### PR TITLE
Mac build improvements

### PR DESCRIPTION
**Pull request by jakepetroules**

### CODE REVIEW

**Comment by benmccann** [comment]
Please be sure to update the wiki after this is merged: https://github.com/symless/synergy/wiki/Compiling

**Comment by benmccann** [comment]
@XinyuHou @nbolton would you be able to merge this PR?

**Comment by benmccann** [comment]
ping @XinyuHou @nbolton

**Comment by XinyuHou** [comment]
This PR would fix #5297

**Comment by XinyuHou** [comment]
@jakepetroules 
I can't seem to create a branch for this PR.

**Comment by benmccann** [comment]
What do you mean? I don't understand why you wouldn't be able to or why you have to in the first place. Don't you just hit the "Merge pull request" button?

**Comment by legonigel** [comment]
@benmccann It appears that @jakepetroules deleted his repository, so that although the PR is still open, the code doesn't exist. This prevents @XinyuHou from cloning the PR into a branch. The reasoning for moving this to a branch is that the build bot can build the branch, providing installers for testing. All PRs should be tested before being merged.

**Comment by jakepetroules** [comment]
Just apply the diff manually by copying it from the web interface here. It's pretty minimal.

**Comment by XinyuHou** [comment]
Cherry-picked in https://github.com/symless/synergy/tree/v1.8.3

**Pull request closed without merging**
