### PR TITLE
Update mac instructions to install zip distribution

### PR DESCRIPTION
**Pull request by beefnog**
I updated the directions such that a clear installation path is provided that does not require the direct use of root.

### CODE REVIEW

**Comment by XinyuHou** [comment]
@beefnog 
What is the advantages of doing as user then change permission over doing as root in the first place?

**Comment by beefnog** [comment]
The advantage is that performing the operations using sudo actually requires fewer steps than activating the root user to perform the installation. Additionally, Installing the software using sudo does not require making persistent user account changes to the system.

**Comment by dgentry** [comment]
It is still generally considered better practice to make changes using sudo than to become root, so this change would still be helpful.

**Comment by dgentry** [comment]
Thanks!

**Comment by XinyuHou** [comment]
Merged into v1.8.6

**Pull request closed without merging**
