### PR TITLE
Fix for Issue #5648 - Mouse Drifting/Jittering/Lagging

### PR DESCRIPTION
**Pull request by frankrue**
Fix for Issue #5648, using proposed code from @PutzWorks. Also includes compilation fixes to allow compiling on Sierra (unfortunately, I was only able to implement the fix with QT4). Tested on my two Macs, both of which were exhibiting the mouse problem, and are now no longer exhibiting the problem with this new build.

### CODE REVIEW

**Comment by frankrue** [comment]
@nbolton - I couldn't find a contributing doc, so I may be asking for a PR for the wrong branch, or you may want me to handle my commits differently. Just let me know.

**Comment by PutzWorks** [comment]
@frankrue I hope I'm not too late, but could you please make the same CGFloat change to the MouseWheel function as well?  The mouse wheel suffers from the same int rounding and is slightly irritating to deal with when coding on my Windows PC.

**Comment by LoungeFlyZ** [comment]
hi @nbolton, any update on when this issue will be addressed?  As a diehard paying fan it's a very tough bug to deal with right now.

Surely this is a stop everything and fix type of bug no?  The user base is only getting bigger and bigger as people move to Sierra.

A solid plan to fix and timeline would be GREATLY appreciated by your fans.

**Comment by LoungeFlyZ** [comment]
Is there any chance of a private build drop for this?  It's driving many nuts... and i would happily run a private build until it hits the next release.

**Comment by nlyan** [comment]
We're busy working on Synergy v2 right now, but I've pushed a build that should be available at the following URL soon

https://symless.com/nightly?filter=1c1067d

**Comment by w1nterl0ng** [comment]
As Far as I can tell this seems to have resolved the most obvious symptom.  I don't know enough about the problems everyone is having to speak definitively, for the moment this seems to be working.

**Comment by kekkokk** [comment]
the link is outdated and this fix NEED to be merged in stable release for all the people that have Sierra.
Stable release using sierra + ext. mouse in NOT usable atm and the fix is out since months. 
it's a 10 minute job. pls, do something

**Comment by nbolton** [comment]
Temp fix: https://github.com/symless/synergy-core/files/902511/synergy-v1.8.8-pr-5648-stable-1c1067d-MacOSX-x86_64.dmg.zip

**Comment by kekkokk** [comment]
@nbolton Could you please merge in v2? it's been more than a year now, how the f is possible you haven't merged this core fix in a year?
All mac os user that uses an external mouse in the host (osx) suffer from this issue. How can you ignore that???

**Comment by nbolton** [comment]
This PR is urgent priority for Synergy 2.

**Pull request merged**
