### PR TITLE
force XSync to help key repeat detection

### PR DESCRIPTION
**Pull request by Unknow0**
this avoid miss in key repeat detection.

### CODE REVIEW

**Comment by XinyuHou** [comment]
@Unknow0 
Could you give us some insight of your changes?

**Comment by Unknow0** [comment]
I noticed some time the detection of key repeat fail.

When i looked into it the way you detect the key repeat should works.
The only way to miss the key repeat is if the KeyPress isn't in the event queue.

So i added a call to XSync to retreive all event before looking for the KeyPress event.

**Comment by XinyuHou** [comment]
@Unknow0 
Please test this nightly
http://symless.com/nightly?filter=linux-key-repeat-rc2-03ec531

**Comment by XinyuHou** [comment]
@Unknow0 
Sorry, it seems this PR doesn't solve the problem.
https://github.com/symless/synergy/issues/4658#issuecomment-265192845

**Pull request closed without merging**
