### PR TITLE
Dragging broken in Unity (mouse movement deltas missing)

### PR DESCRIPTION
**Pull request by jpmcmu**
OSXScreen was not adding mouse movement deltas to mouse events while
dragging. Some 3D applications rely on these deltas to implement
dragging. Adding the mouse deltas to the mouse event fixes dragging in
these applications. Ex: Unity3d

Fixes Bug: #3992

### CODE REVIEW

**Comment by nbolton** [comment]
Thanks for the pull request! Buildbot is now [building](http://buildbot.synergy-project.org/builders) this PR, which usually takes about 30 minutes. When done, it'll upload the packages to our [nightly builds page](http://synergy-project.org/nightly?filter=pr-jpmcmu-mouse-move-deltas-fix). Happy testing!

**Comment by XinyuHou** [comment]
@jpmcmu 
It is conflicting now. Could please fix it?

**Comment by elasim** [comment]
It worked without one of them and float value is our best choice I think.
also, the cursor will shake between two points on Blender.

Anyway, it's always better than making mess up my desk.

**Comment by XinyuHou** [comment]
@jpmcmu 
Thank you for the pull request.

Would you mind fix the conflict and the indentation problem? Then I will create a branch for testing again.

**Comment by ttay24** [comment]
Did this ever get fixed? I just downloaded Synergy and this is still an issue. Build says it's from yesterday (10-26-2016)

**Comment by jpmcmu** [comment]
@XinyuHou The conflict and indentation issues have been resolved.

**Comment by nlyan** [comment]
Merged in v1.8.8

**Pull request closed without merging**
