### PR TITLE
Add _XKEYCHECK_H to preprocessor definitions

### LINKED ISSUE #4388: Add _XKEYCHECK_H to preprocessor definitions
After running `hm conf -g1` and then opening the solution in VS2013, I get complaints from every project:

```
Error   3   error C1189: #error :  The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro.
```

Adding `_XKEYCHECK_H;` to each project's properties (C/C++ > Preprocessor > Proprocessor Definitions) removes this error. Perhaps this should be added to `/CMakeLists.txt`

### PR DESCRIPTION
**Pull request by JoshMcCullough**

### CODE REVIEW

**Comment by nbolton** [comment]
@JoshMcCullough Which warning does this solve?

**Comment by JoshMcCullough** [comment]
Without it, I get 133 of these when building in VS12 (note that's *errors*, not *warnings*):

    Error	369	error C1189: #error :  The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro.

Here's the full list with paths: https://gist.githubusercontent.com/JoshMcCullough/64de66ff330ff770ca89/raw/fa40f1392023b254308183189f37291e27b0f85e/gistfile1.txt

**Comment by JoshMcCullough** [comment]
See [this thread](https://github.com/synergy/synergy/issues/4246#issuecomment-86897835) as well.

**Comment by XinyuHou** [comment]
@JoshMcCullough 
Thank you for the pull request.

Is there an issue associated to this pull request?

**Comment by JoshMcCullough** [comment]
#4264, #4371

**Comment by XinyuHou** [comment]
Made redundant by #4978

**Pull request closed without merging**
