### PR TITLE
Update Server.cpp with @neworld mouse speed enhancement

### PR DESCRIPTION
**Pull request by spurin**
Credit to @neworld and https://github.com/neworld/personal-aur-synergy/blob/master/trunk/adjust_low_dpi_mouse_speed.patch

Relates to the issue: https://github.com/symless/synergy/issues/4245

### CODE REVIEW

**Comment by nbolton** [comment]
> [Update codeql-analysis.yml to use ubuntu-24.04](https://github.com/symless/synergy/pull/7508/commits/d8f676c5ebd77ad9dabde3e486cb33b3e456c60b)

Oh, thanks, I had been meaning to get to that.

**Comment by nbolton** [comment]
> > [Update codeql-analysis.yml to use ubuntu-24.04](https://github.com/symless/synergy/pull/7508/commits/d8f676c5ebd77ad9dabde3e486cb33b3e456c60b)
> 
> Oh, thanks, I had been meaning to get to that.

Edit: Ah, actually, it looks like it was already using the Ubuntu 24 runner (`ubuntu-24.04-16-core-x64`), but it's using the faster paid one that only maintainers have access to. I think we should add a flag that uses the slower runner when a contributor kicks off a build. I'll do that in a separate PR.

**Comment by nbolton** [comment]
> Update ci.yml change runner to windows-2022

Could you let me know what's the thought behind this? The `windows-2022` runner is the free one, whereas `windows-2022-8-core-x64` is the faster paid one.

**Comment by spurin** [comment]
Apologies, this is me trying to work around the build challenges with windows by experimenting with the runner myself. That said, it could be beneficial to the community if they can use the CI to automate builds.

I can move the Server.cpp change into it's own fork if preferred, let me know how you'd prefer to proceed.

**Comment by spurin** [comment]
For reference, whilst I didn't initially intend to include the runner changes that I was experimenting with (I blame the lack of coffee), it seems to be going well so far - https://github.com/spurin/synergy/actions/runs/10828057969/job/30042563838

**Comment by spurin** [comment]
The windows CI run using this approach worked. A happy mistake, as per the discussion we have underway at: https://github.com/symless/synergy/discussions/7504

In the build documentation, having a guide on using the CI workflow could be easier and more productive for some people on windows.

**Comment by nbolton** [comment]
No apology necessary, just Cunningham's Law at play here. It's really useful that you made these CI changes because it highlighted a problem with how our CI I set up.

I'm working on this problem now. I'll update here when I open my PR.

**Comment by nbolton** [comment]
@spurin Ok, here's what I have so far: https://github.com/symless/synergy/pull/7509

**Comment by nbolton** [comment]
@spurin Ah, did you intend to close this PR or was that accidental?

**Comment by nbolton** [comment]
> I reset my branch as I'm going to test the CI process that you shared and see if I can get a build working on Windows.

Ah, I merged the CI changes into this PR. So, it should have produced a binary.

Do you plan to re-open this PR or create a new PR?

**Comment by nbolton** [comment]
For posterity, development continued in https://github.com/symless/synergy/pull/7511

**Pull request closed without merging**
